//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.booking_journal = new HashSet<booking_journal>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_author { get; set; }
        public Nullable<System.DateTime> date_public { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<int> genre { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<bool> published { get; set; }
        public Nullable<int> penalty_points { get; set; }
        public Nullable<int> tags { get; set; }
    
        public virtual author author { get; set; }
        public virtual genre genre1 { get; set; }
        public virtual tag tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_journal> booking_journal { get; set; }
    }
}
