//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingJournal
    {
        public int id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string bookingCode { get; set; }
        public int status { get; set; }
        public int idReader { get; set; }
        public int idBook { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
