//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookingJournals = new HashSet<BookingJournal>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idAuthor { get; set; }
        public Nullable<System.DateTime> datePublic { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<int> genre { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<bool> published { get; set; }
        public Nullable<int> penaltyPoints { get; set; }
        public Nullable<int> tags { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre1 { get; set; }
        public virtual Tag Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingJournal> BookingJournals { get; set; }
    }
}
