//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_journal
    {
        public int id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string booking_code { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_reader { get; set; }
        public Nullable<int> id_book { get; set; }
    
        public virtual book book { get; set; }
        public virtual reader reader { get; set; }
        public virtual status status1 { get; set; }
    }
}
