//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id_user { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> id_reader { get; set; }
    
        public virtual reader reader { get; set; }
        public virtual role role1 { get; set; }
    }
}
