//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> idReader { get; set; }
    
        public virtual Reader Reader { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
